name: CI/CD Deployment to GKE

on:
    push:
        branches:
            - main

env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    GKE_CLUSTER: "weather-app-cluster"
    GKE_REGION: "us-central1"
    DEPLOYMENT_NAME: "weather-rain-prediction-app"
    REPOSITORY: "us-central1-docker.pkg.dev/weather-rain-prediction/weather-rain-repo"
    IMAGE: "us-central1-docker.pkg.dev/weather-rain-prediction/weather-rain-repo/weather-rain-prediction-app"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - id: 'auth'
              uses: google-github-actions/auth@v2
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Set up gcloud
              uses: google-github-actions/setup-gcloud@v2
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
            
            - name: Train Model
              run: |
                python3 -m pip install --upgrade pip
                pip3 install -e .[dev]
                python3 pipeline/training_pipeline.py

            - name: Authenticate Docker to Artifact Registry
              run: |
                gcloud auth configure-docker us-central1-docker.pkg.dev

            - name: Building and Pushing Image
              run: |
                docker build -t $IMAGE:$GITHUB_SHA .
                docker push $IMAGE:$GITHUB_SHA

            - name: GKE Configuration
              run: |
                gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_REGION --project $PROJECT_ID

            - name: Deploying to Kubernetes
              run: |
                kubectl apply -f kubernetes-deployment.yaml
                kubectl set image deployement/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$IMAGE:$GITHUB_SHA
                
